Upgrade `jackson-module-kotlin` package to 2.17.1. The previous version was causing a `NoClassDefFoundError` error due to an incompatibility with DGS.